### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#137]
## Summary
Add a new [404 page](https://help.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site) to this portfolio. 

### Motivation
Nearly all webpages have it. 

### Additional context
https://help.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
The above link explains how to add it in a Github Pages. Further, supporting Netlify and Versel is also needed. I think a `.htaccess` would do.

**Comment by naveen521kk** [comment]
What do you think about it @saadpasta and @kartik918  ?

**Comment by kartik918** [comment]
This, although being a good addition to any website, isn't related or useful to ours at all.

Since ours is a "webpage" or an SPA and not a website, we don't require a 404 throwback. It's either browser finds the URL, or it doesn't which would throw back to GH pages 404 which does the job. There's no outbound links from the app as of now

However, if we ever move away from being an SPA (which in my opinion we shouldn't) we can keep this idea in mind.

Good thought, thanks!
