### ISSUE TITLE
Using Projects

### ISSUE THREAD

**Issue by naveen521kk** [saadpasta/developerFolio#153]
I think it would be good if start using [Github Project](https://github.com/saadpasta/developerFolio/projects). We can just our project goal ( maybe creating new *components* ) or organize issues. I just your opinion about this @saadpasta and @kartik918.

**Comment by kartik918** [comment]
While it's a good idea, it isn't ideal for small to medium scale "passion" projects. We don't have long term goals about the projects or any direction for it since it's something we all are creating together in our free time.
GH Projects are better suited for software or project development with teams working on different stuff together whereas we are loosely working and building on suggestions and work from the community and what they would like to see added to the project.

Right now, we can track issues and PRs effectively. I'll bring it up again when this turns into something massive. Thanks for the suggestion!
