### ISSUE TITLE
Resume Editable from live website

### ISSUE THREAD

**Issue by AyyanNiazi** [saadpasta/developerFolio#189]
## Summary
I think it should editable from live website like every should able to create its own resume as per its skills and Education and also resume should be download . Like if someone dont want whole portfolio and he/she want only resume and most of the cases it make sense 

### What's new?
Templates for Resume
Resume Downloader  (PDF)

### Motivation
i am interesting to do this whole part with your help

**Comment by saadpasta** [comment]
@AyyanNiazi that's a great idea. But for this, we have to change our whole codebase and I think this is a complete project in itself. If you would like to create something like this you can take the DeveloperFolio code and start working on it and publish the project on your profile. We. would love to help and see how this turns out. ✌️
