### ISSUE TITLE
Token revoked when deploying to gh-pages 

### ISSUE THREAD

**Issue by martiriera** [saadpasta/developerFolio#320]
Hello Saad and the rest of contributors. First of all congratulations for this work, very fancy stuff!

I have a master branch with a source code and a gh-pages one for the deployment. The thing is that when I execute the `npm run deploy` from master branch, GitHub detects the access token on a commit and revokes the token.

As stated on issue #180 I have the .env file on the .gitignore of the master branch. I am also defining the secret on the repo.

Any idea? I am missing something?

Thank you.

**Comment by Matesanz** [comment]
It is also happening to me. If I use the **token while developing there's no problem**, everything works fine.
If I run the `npm run deploy` and before entering the credentials I run `serve -s build` everything is ok.
BUT, **when deploying to gh-pages** the problem faces: the **token disappears...**

**Comment by saadpasta** [comment]
@martiriera make sure your .env file is in .gitignore. Try to generate a new token and try again or use another method of converting the token to base64 and then converting it back to normal when using so Github doesn't detect it

**Comment by martiriera** [comment]
@saadpasta thanks for your answer. 

I am sure that my .env is not pushed. What is really happening is that the token appears in plain text on a file commited in "gh-pages", here an example: [https://github.com/martiriera/martiriera.github.io/blob/8a7caed452fca1217a9c11f1eed8c772eb196cd9/static/js/main.be129e4c.chunk.js ](url)
I tried to encrypt the token when using it on the app but it continues appearing on this "main" chunk. 

Maybe my deployment is not correct? It's something related to the repo secret?

Thanks for your time.

**Comment by harikesh409** [comment]
As stated in the [create-react-app](https://create-react-app.dev/docs/adding-custom-environment-variables/) the token will be visible in the static files once it is builded, that is the reason github is removing it.

```
WARNING: Do not store any secrets (such as private API keys) in your React app!
Environment variables are embedded into the build, meaning anyone can view them by inspecting your app's files.
```

**Comment by martiriera** [comment]
@harikesh409 thanks for your answer.

As stated [here](https://stackoverflow.com/a/57103663/14983877) the only way to do so is making a request to a back-end API. Is there a way to do it with the tools used on this portfolio (GitHub Actions, repo secrets)?

**Comment by naveen521kk** [comment]
> Is there a way to do it with the tools used on this portfolio (GitHub Actions, repo secrets)?

You would need a server, which isn't the aim of this project, so something must be done by maintainers to fix this, possibly the best I can think is to do something while building the site itself, say a script to fetch things from GitHub API and save it in a JSON file which will be build while deploying and use it to show the needed contents instead of querying the Github API client-side. Any idea @kartikcho 

cc @saadpasta

**Comment by kartikcho** [comment]
That is a better idea than what we're currently doing but the current solution _should_ work. 

Storing token in Github repo env variables should have no problem while building but it seems like the people who are facing this issue are the ones who are using gh pages to host their site which hosts from a branch with the prebuilt react app that has access to the env variable locally during build time (I could be wrong about this hypothesis, this is one explanation that came to my mind). 

Can you confirm @martiriera that you're facing something similar when hosting from Netlify or Vercel with respective proper setups?

**Comment by naveen521kk** [comment]
Any how anybody can inspect the request and the token can be leaked. The idea I told could possibly fix this, and I will be working this week implementing it.

**Comment by harikesh409** [comment]
> > Is there a way to do it with the tools used on this portfolio (GitHub Actions, repo secrets)?
> 
> You would need a server, which isn't the aim of this project, so something must be done by maintainers to fix this, possibly the best I can think is to do something while building the site itself, say a script to fetch things from GitHub API and save it in a JSON file which will be build while deploying and use it to show the needed contents instead of querying the Github API client-side. Any idea @kartikcho
> 
> cc @saadpasta

@naveen521kk But if you do this then the content coming from the GitHub will be static and if you have new contributions from GitHub you need to rebuild your project and redeploy it. Correct me if I am wrong.

**Comment by naveen521kk** [comment]
> But if you do this then the content coming from the GitHub will be static

Yeah, it should be static, maybe we can set up Github Action, using the scheduled workflow so that users can use that to redeploy their site automatically every week or so. Or rather use [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) so that users can redeploy their site in one click whenever they edited their information on Github. Also, I don't people will use change pinned repos frequently also not edit their bio or something more frequently.

>  Instead we can use this endpoint https://api.github.com/users/username/repos to get the public repos.

This is rate limited...
Also, there isn't information about pinned repositories there. So, this can't be used to get pinned repos...
Also, initially, when I implemented the profile section in https://github.com/saadpasta/developerFolio/pull/113, I used public API available it caused much error because Github's API is rate-limited, done in https://github.com/saadpasta/developerFolio/pull/184

**Comment by martiriera** [comment]
> Can you confirm @martiriera that you're facing something similar when hosting from Netlify or Vercel with respective proper setups?

@kartikcho I can confirm that the token was not revoked by GitHub when I deployed with Netlify, but I'm not sure if it is still exposed.

**Comment by martiriera** [comment]
The #333 feature works for me. Great work @naveen521kk. You guys can close this issue if you want. Thanks, bye!

**Comment by kartikcho** [comment]
Great to hear that @martiriera but did you test the changes in that PR in your fork locally as they're not in main yet.
Regardless, good stuff Naveen!
