### ISSUE TITLE
npm run test is failing

### ISSUE THREAD

**Issue by shoebsd31** [saadpasta/developerFolio#349]
**Describe the bug**
when tests are run, select all, the test suite for App.test.js fails

**To Reproduce**
1. Go to command line
2. install all dependencies by running 'npm install'
3. run the following command 'npm run test'
4. select all test cases
5. See error " Cannot set property 'fillStyle' of null"

**Expected behavior**
the test should pass

**Is this responsiveness Issue**
NO

**Screenshots**
![image](https://user-images.githubusercontent.com/5415085/113505442-26b7f380-953f-11eb-8850-63ffd641e907.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser CHrome

**Comment by kartikcho** [comment]
@shoebsd31 have you turned off lottie (animated illustrations) in `portfolio.js` for your app

**Comment by shoebsd31** [comment]
Hi @kartikcho ,

I just followed the steps in the documentation and executed

 npm run test.

**Comment by kartikcho** [comment]
Alright, I'll take a look at this and see what's up. Thanks for reporting this!

**Comment by Anshluthra1** [comment]
unable to run npm start. elifice error. pls help.


<img width="1440" alt="Screenshot 2021-04-12 at 12 27 10 AM" src="https://user-images.githubusercontent.com/76260663/114341517-98afbe80-9b77-11eb-9bd7-d23044b37df8.png">

**Comment by kartikcho** [comment]
Did you create a `.env` file with your gh access token as mentioned in the docs and the error logs @Anshluthra1?

**Comment by Anshluthra1** [comment]
No sir i didnt

**Comment by Anshluthra1** [comment]
Can you do me a favor?

**Comment by Anshluthra1** [comment]
Can you send me a normal zipped folder of this developer folio, I'll edit that according to my own! Pls

**Comment by Anshluthra1** [comment]
??

**Comment by kartikcho** [comment]
You can do that for any repositories from here but you should fork it first imo

![image](https://user-images.githubusercontent.com/48270786/114357544-7aee5380-9b8f-11eb-8ec8-6bf22f7cc6c0.png)

**Comment by kartikcho** [comment]
I dug around this issue over the weekend and the reason is we're missing a test module dependency as discussed [here](https://github.com/chenqingspring/react-lottie/issues/66).

The default react-scripts test config doesn't support the `setupFiles` property that we need. We could eject from CRA to use manual configs (although it will introduce a bunch of configs and increase complexity of the project). I'll see if there's any other workaround to get custom configs to work without ejecting.

Might dig around for a better solution more this weekend.
