### ISSUE TITLE
Github Pages Deploys README.md

### ISSUE THREAD

**Issue by LilCrispyVal** [saadpasta/developerFolio#387]
I've tried so hard to find out what the bloody hell is the problem with this, but I can't seem to find the source of why whenever I deploy a github, it always deploys the README.md do you have a video or can you give a detailed description to why it's doing this?

**Comment by naveen521kk** [comment]
Didn't Github Actions deploy it?

**Comment by naveen521kk** [comment]
Hmm, ok that action is missing, and I removed it by mistake sorry, will add it back.

**Comment by LilCrispyVal** [comment]
Do I need to git clone again?

**Comment by LilCrispyVal** [comment]
Cause cloning it leads me to remote: Permission to saadpasta/developerFolio.git denied to LilCrispyVal. Etc etc. So I downloaded it via zip folder.

**Comment by kartikcho** [comment]
Hey @LilCrispyVal, you should fork it to your own account first and then clone that fork to your environment. You may also update your fork from this repo from time to time to stay up-to-date with the new changes here.

Also, wait for the linked PR to get merged before you do so to have the issue fixed in your version of the repo.
