### ISSUE TITLE
Add instructions to customize Lottie animations in the docs

### ISSUE THREAD

**Issue by MrAsimZahid** [saadpasta/developerFolio#404]
Hi,

I want to change SVGs/image appearing on the right side of screen. How can I do it?

Secondly, on the top left corner, I want to keep the old signature look of the name like [here](https://developerfolio.js.org/). How can I do it?

![portfolio screen](https://user-images.githubusercontent.com/23510373/132138790-7224f53e-7e74-43d2-a10d-87241beeea26.png)

**Comment by kartikcho** [comment]
Sorry for the late answer, I hope this helps if you haven't already figured this out.

1) The SVG animations are displayed using Lottie. Checkout https://lottiefiles.com/ to find more animations and add them in `src/assets/lottie`. Then replace them wherever the existing ones are being used in the components.

2) This was an old bug that has been fixed in the recent versions. Pull the latest changes to your fork from this repo to fix it for your app too.

We should update the documentation to add a line explaining where to change Lotties for future users, thanks!

**Comment by MrAsimZahid** [comment]
I have changed it. I found the animated boolean option in portfolio.js. Although, what you have defined is also important.

**Comment by RedHeadphone** [comment]
by docs you mean README.md right ? Can I add it ? Also it should come after https://github.com/saadpasta/developerFolio#using-emojis right?

**Comment by kartikcho** [comment]
Yeah that sounds good. Link to https://lottiefiles.com/ and mention how users can find new Lotties there, how to insert your own Lottie json animation and cover a bit about the options available in the `react-lottie` library.

Assigning this to you @RedHeadphone!

**Comment by RedHeadphone** [comment]
this will do ?

#### Customize Lottie Animations

You can choose a lottie and download it in json format from [this page](https://lottiefiles.com/). In `src/assets/lottie`, replace the lottie json file you want to alter with the same file name. If you want to change the lottie options, go to `src/components/displayLottie/DisplayLottie.js` and change the `defaultOptions` object.

**Comment by kartikcho** [comment]
@RedHeadphone just open a PR, we can discuss what's good during the reviews!
