### ISSUE TITLE
A way to add custom svg icons that aren't in Font Awesome website

### ISSUE THREAD

**Issue by marcpinet** [saadpasta/developerFolio#439]
## Summary
A way to add custom svg icons (using relative path) that aren't in Font Awesome website.

### What's new?
Currently, we can't to this. We can only use fontawesome icons and they're mostly outdated or lacking.

**Comment by kartikcho** [comment]
Sorry for the late reply @marcpinet! 
You can do it but you'd need to tweak the code manually in [`src/components/softwareSkills/SoftwareSkill.js`](https://github.com/saadpasta/developerFolio/blob/master/src/components/softwareSkills/SoftwareSkill.js) to use custom icons instead of using `portfolio.js` using the fa ones.

**Comment by marcpinet** [comment]
> Sorry for the late reply @marcpinet! You can do it but you'd need to tweak the code manually in [`src/components/softwareSkills/SoftwareSkill.js`](https://github.com/saadpasta/developerFolio/blob/master/src/components/softwareSkills/SoftwareSkill.js) to use custom icons instead of using `portfolio.js` using the fa ones.

Hello, thank you for your answer. Do you have any idea about how can I do that? I'm a newbie at JS so I don't really have any idea about how to do that.

Thank you in advance!

**Comment by kartikcho** [comment]
There are multiple ways to do it like using another external icon library (different from FA) or importing your own custom SVGs (which I assume is what you're asking). 

You can remove all of the part below and just use your own imported icons list directly
```jsx
{skillsSection.softwareSkills.map((skills, i) => {
      return (
        <li
          key={i}
          className="software-skill-inline"
          name={skills.skillName}
        >
          <i className={skills.fontAwesomeClassname}></i>
          <p>{skills.skillName}</p>
        </li>
      );
    })}
```

Since we've used create-react-app to build this app, you can import SVGs like `import icon from '../iconlocation/icon.svg`
and then use it directly in your code like,
```jsx
    <li
      className="software-skill-inline"
      name="Skill name"
    >
      <icon />
      <p>Skill name</p>
    </li>
```

[This blog](https://betterprogramming.pub/create-react-app-and-svgs-70970ac715f2) covers most of the other ways to do it if the above doesn't help.

**Comment by marcpinet** [comment]
> There are multiple ways to do it like using another external icon library (different from FA) or importing your own custom SVGs (which I assume is what you're asking).
> 
> You can remove all of the part below and just use your own imported icons list directly
> 
> ```js
> {skillsSection.softwareSkills.map((skills, i) => {
>       return (
>         <li
>           key={i}
>           className="software-skill-inline"
>           name={skills.skillName}
>         >
>           <i className={skills.fontAwesomeClassname}></i>
>           <p>{skills.skillName}</p>
>         </li>
>       );
>     })}
> ```
> 
> Since we've used create-react-app to build this app, you can import SVGs like `import icon from '../iconlocation/icon.svg` and then use it directly in your code like,
> 
> ```js
>     <li
>       className="software-skill-inline"
>       name="Skill name"
>     >
>       <icon />
>       <p>Skill name</p>
>     </li>
> ```
> 
> [This blog](https://betterprogramming.pub/create-react-app-and-svgs-70970ac715f2) covers most of the other ways to do it if the above doesn't help.

And is there a way to use FontAwesome 6 instead of the 5.15 used?

**Comment by kartikcho** [comment]
You can see how to do it in detail in the [FontAwesome docs](https://fontawesome.com/v5.15/how-to-use/on-the-web/referencing-icons/basic-use) but it seems FA6 is still in beta.

**Comment by techiesalman** [comment]
@marcpinet you can try https://devicon.dev/

Here you will get some other icons that are not available in FontAwesome. You need to add their CDN in index.html and insert icon name same like FA and your job will be done.

**Comment by marcpinet** [comment]
> @marcpinet you can try https://devicon.dev/
> 
> Here you will get some other icons that are not available in FontAwesome. You need to add their CDN in index.html and insert icon name same like FA and your job will be done.

It worked, thanks!
