### ISSUE TITLE
Failed to compile due to a syntax error in `./src/containers/projects/Projects.js`

### ISSUE THREAD

**Issue by wehs7661** [saadpasta/developerFolio#451]
**Describe the bug**
Hi,
I'm new to this template and I followed the instruction in `README` to install all packages required for the template. However, after executing `npm start`, I got the following error. 

```
Failed to compile.

Error in ./src/containers/projects/Projects.js
Syntax error: Unexpected token (9:4)

   7 | export default function Projects() {
   8 |   const GithubRepoCard = lazy(() =>
>  9 |     import("../../components/githubRepoCard/GithubRepoCard")
     |     ^
  10 |   );
  11 |   const FailedLoading = () => null;
  12 |   const renderLoader = () => <Loading />;

 @ ./src/containers/Main.js 34:16-46

Error in ./src/containers/profile/Profile.js
Syntax error: Unexpected token (8:2)

   6 | const renderLoader = () => <Loading />;
   7 | const GithubProfileCard = lazy(() =>
>  8 |   import("../../components/githubProfileCard/GithubProfileCard")
     |   ^
   9 | );
  10 | export default function Profile() {
  11 |   const [prof, setrepo] = useState([]);

 @ ./src/containers/Main.js 74:15-43
```
I'd edited `.env` file to update my GitHub username and token before executing the command. My versions of my `node` and `npm` are `v16.13.1` and `8.1.2`, respectively. Please let me know if there is further information I should provide to troubleshoot. I apologize if this question is too naive. Thank you!

**Is this responsiveness Issue**
NO

**Comment by kartikcho** [comment]
Hey @wehs7661, sorry for the late reply! 

I just pulled the latest master and was able to run it without any issues. However this could be an issue since it is obviously happening for you.

I would suggest to make a new clean clone of the template with no changes or additions like adding an environment variable (even though that shouldn't be the cause of the error). 

Simply run `npm install` and then `npm start` and let me know if it still throws an error. Otherwise you can continue changing portfolio's content with the dev server on and see what caused things to break.

**Comment by CodeLikeAGirl29** [comment]
No that import statement is in the wrong place! Just copy that whole line and put it with the other 'import' statements!

**Comment by wehs7661** [comment]
Making a new clean clone did work! I think I accidentally modified `package-lock.json` and `package.json`. (I don't really remember what I might have changed though.) Thanks a lot for the reply!

**Comment by kartikcho** [comment]
@CodeLikeAGirl29 it isn't in the wrong place 😅 , we're using dynamic imports for the `GithubRepoCard`, you can read more about it [here](https://reactjs.org/docs/code-splitting.html#reactlazy).
No problem, glad that your issue was resolved @wehs7661!
