### ISSUE TITLE
Add Dark Mode Option 🌙

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#55]
Most applications nowadays have dark mode and it kinda looks cool so I guess we should implement Dark Model in DeveloperFolio.

**Comment by kartik918** [comment]
Great idea but some stuff to consider,

Many graphics have white backgrounds instead of being transparent so that might be an issue to tackle while switching colors. Maybe update them by removing whites manually?

To test or get an idea how the dark mode should look, try viewing the website after turning on Dark Reader extension. Will help in testing and getting contrast ideas

**Comment by pratikms** [comment]
Hey @saadpasta ,

First of all, thank you so much for this awesome awesome project. I wanted to quickly get started with a portfolio, and all other options, including purchasing a paid template as well as building one from the scratch seemed too much of a task to me.

The way you've designed the project helped me to get up and running in no time. Your project structure is quite extensible and made me feel at home because of which I was able to quickly do some tweaks to it according to my preference and publish a portfolio as per my requirements.

I'd love to contribute back. I saw this issue and wanted to bring some attention to a couple of changes I've made. I don't know if it would qualify as a purely 'dark' mode, but the changes I did are available in my forked repo.

Right now my hands are full, but whoever finds time can make those changes in the styling that I made with their desired values and get this issue closed. If no one is available, I will take this up myself and contribute in whatever way I can.

My version of a potention dark mode is available at http://pratikms.com/ and the code for the same is available on my [forked repo](https://github.com/pratikms/developerFolio).

A lot of work still needs to be done and I am still in the process of constantly updating the site. But any constructive feedback w.r.t. this issue or any issue in general is welcome.

**Comment by saadpasta** [comment]
@pratikms Thank You very much for these kind words. Means a lot. Love the tweaks you have done with DeveloperFolio I guess it is pretty nice. I know it needs a lot of work and we can discuss it here under this issue and get started with basics.

**Comment by abuyako** [comment]
Yes I am agreed with you, Dark Mode is one of the cool future and everyone knows that, even in our code editors that we using everyday we all like that future too.

**Comment by abhishekashyap** [comment]
Can I take this up?

**Comment by kartik918** [comment]
Thanks for your interest @abhishekashyap but we already have an outstanding PR in progress by @MohammadHasham in #92.

I'll add him as an assignee to clear up further confusion.

**Comment by kartik918** [comment]
@MohammadHasham can you drop a comment here so I can assign this to you?

**Comment by MohammadHasham** [comment]
Yeah sure!

**Comment by sartz18** [comment]
can I also work on this?

**Comment by oshinsaini** [comment]
can I also work on this? 
If yes, please assign this to me

**Comment by kartikcho** [comment]
Thanks for your interest @oshinsaini but we already have an outstanding PR in progress in #92. You can look into other open issues if you would like to contribute!

**Comment by naveen521kk** [comment]
Fixed in #92
