### ISSUE TITLE
Should we add Dependabot 🤖

### ISSUE THREAD

**Issue by saadpasta** [saadpasta/developerFolio#62]
As we have a lot of packages and we need to keep them updated so should we add Dependabot.

Dependabot is an automation service that will automatically create PRs to keep your project's dependencies up to date and I think it kind of good if we add this and keep our dependencies updated. 

https://github.com/marketplace/dependabot-preview

@kartik918

**Comment by naveen521kk** [comment]
Maybe yes.

**Comment by kartik918** [comment]
Great idea but I don't think it would make a difference since the project is self contained and complete with the current versions of packages.

It would be good practice to use latest dependencies but newer package versions might cause regressions with the existing code that we may have to refactor to later.

I'm for the decision, just something to keep in mind.

**Comment by kartik918** [comment]
So what do you think about going with this now @saadpasta ? Should we, or should we close it unless we need it.

**Comment by saadpasta** [comment]
@kartik918 don't think we need it.
